### ISSUE TITLE
Class definitions may need design change

### ISSUE THREAD

**Issue by szimmer1** [camargo/tracejs#5]
GeometricObject.js
```javascript
(function () {
    'use strict';

    var GeometricObject = function (color) { // Argument Type: (RGBColor).
        this.color = color;
    };

    GeometricObject.prototype.hit = function (ray, tmin, shadeRec) { // Argument Types: (Ray, float, ShadeRec)
        return false;
    };
}());
```
I see a possible downfall in this class design since GeometricObject() is contained in a self-executing function, its scope won't be visible to the other files. Importantly, Sphere.js will try to assign GeometricObject as its prototype but will fail because GeometricObject will be undefined for it. 

A possible solution may be introducing a single global object Tracejs outside of the self-executing function and then adding all our objects to it:
```javascript
var Tracejs = Tracejs || {}    // If Tracejs is defined then reference it, if not create empty object

(function () {
    'use strict';

    Tracejs.GeometricObject = function (color) { // Argument Type: (RGBColor).
        this.color = color;
    };

    Tracejs.GeometricObject.prototype.hit = function (ray, tmin, shadeRec) { // Argument Types: (Ray, float, ShadeRec)
        return false;
    };
}());
```

Not sure if this will cause weird effects in our inheritance model. But we need some way for different files to see each other, and I've seen this pattern used before.

Edit: Just created a branch testing this pattern and it seems to work well. Checkout this [branch] (https://github.com/szimmer1/tracejs/tree/inheritance_pattern) from my fork [https://github.com/szimmer1/tracejs.git](https://github.com/szimmer1/tracejs.git) to test

**Comment by camargo** [comment]
Excellent solution, will test this tomorrow

**Comment by camargo** [comment]
Looking into using RequireJS (http://requirejs.org/). It solves the problem of modularizing our application and takes care of this dependecy problem

**Comment by camargo** [comment]
Scratch this. It's probably simpler to do it ourselves.

**Comment by camargo** [comment]
Updated all classes with the recommended pattern
